### ISSUE TITLE
Two GridColumn's can potentially lead to conflicts

### ISSUE THREAD

**Issue by TatuLund** [vaadin/react-components#122]
There is name conflict. You have two GridColumn's

`import { GridColumn } from '@hilla/react-components/GridColumn.js';`

The above is the GridColumn you need in tsx markup in configuring Grid's columns

`import { Grid, GridColumn, GridItemModel } from '@hilla/react-components/Grid.js';`

These are however the imports you need for cellClassNameGenator and cellPartNameGenator , and now here the GridColumn is different from the previous

There is no conflict if you define it as arrow function without types like

```
const classNameGenerator: GridCellClassNameGenerator<Contact> = (column, model) => {
    return assigned.includes(model.item) ? 'bg-primary-100' : '';
}
```

But you can't use normal function like

```
function classNameGenerator(column: GridColumn, model: GridItemModel<Contact>) {
    return assigned.includes(model.item) ? 'bg-primary-100' : '';
}
```

**Comment by TatuLund** [comment]
Another workaround is to use an alias for the import

`import { GridColumn as Column } from '@vaadin/grid';`

**Comment by tomivirkki** [comment]
> But you can't use normal function like

> function classNameGenerator(column: GridColumn, model: GridItemModel<Contact>) {
>    return assigned.includes(model.item) ? 'bg-primary-100' : '';
> }

Instead of `GridColumn`, you should use the `GridColumnElement` type for the web component reference passed to the generator function, for example:

``` ts
import { GridColumn, GridColumnElement } from '@hilla/react-components/GridColumn.js';

function classNameGenerator(column: GridColumnElement, model: GridItemModel<Contact>) {
  return assigned.includes(model.item) ? 'bg-primary-100' : '';
}

```

Closing
