### ISSUE TITLE
Mark headerRenderer as unsupported for GridSortColumn

### ISSUE THREAD

**Issue by web-padawan** [vaadin/react-components#130]
Currently, only `GridFilterColumn` has `headerRenderer` marked as unsupported:

https://github.com/vaadin/react-components/blob/e033b0b0bfb1258a36473534bb51e8806b7649e7/src/GridFilterColumn.tsx#L14-L18

However, the `vaadin-grid-sort-column` element doesn't support `headerRenderer` either, see https://github.com/vaadin/hilla/issues/1097

We should update `GridSortColumn` accordingly to avoid confusion.

**Comment by TatuLund** [comment]
I studied this more, and found another workaround to set title attribute to sorter.

```
        <Grid
          ref={(element) => {
            setTimeout(
              () =>
                element
                  ?.getElementsByTagName('vaadin-grid-sorter')[0]
                  .setAttribute('title', 'Sort by last name and first name'),
              100
            );
          }}
         ---
        >
        ...
        </Grid>
```
