### ISSUE TITLE
Change event for CheckBox never fires

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/react-components#133]
This logs on toggle
```jsx
<input type="checkbox" onChange={(e) => console.log(e)} />
```

This doesn't
```jsx
<Checkbox label="Label" onChange={(e) => console.log(e)} />
```

**Comment by tomivirkki** [comment]
This seems to be an issue with some other field components as well

**Comment by web-padawan** [comment]
This is caused by the fact that `vaadin-checkbox` doesn't contain `change` event in `CheckboxEventMap`. In fact, it doesn't fire custom `change` event, there's just the native one that bubbles. Same applies to `vaadin-radio-group`.
