### ISSUE TITLE
Cookie consent localization doesn't work

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/react-components#136]
Given the following snippet
```jsx
<CookieConsent
  message="Tämä sivusto käyttää evästeitä parhaan kokemuksen tarjoamiseksi"
  dismiss="Selvä"
  learnMore="Lue lisää"
  learnMoreLink="https://vaadin.com/terms-of-service"
/>
```

This still renders as:
<img width="758" alt="Screenshot 2023-08-09 at 14 05 52" src="https://github.com/vaadin/react-components/assets/1222264/6bb4359f-67f9-4a8e-8c6b-fe09994534c5">

**Comment by chrisnaan** [comment]
Hi, I've found this too. It would be nice to be able to add the text that our legal people approve of.

**Comment by cromoteca** [comment]
Duplicate of https://github.com/vaadin/react-components/issues/80

**Comment by tomivirkki** [comment]
> Duplicate of https://github.com/vaadin/react-components/issues/80

Indeed, closing
