### ISSUE TITLE
Component API is not documented

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/react-components#137]
Currently (hovering over a property in VSCode):
<img width="477" alt="Screenshot 2023-08-09 at 14 25 10" src="https://github.com/vaadin/react-components/assets/1222264/bfe6a720-8064-4d84-acfb-3ca7fd74d792">

Expected (documentation is derived from the corresponding web component):
<img width="549" alt="Screenshot 2023-08-09 at 14 24 30" src="https://github.com/vaadin/react-components/assets/1222264/b256ae83-6ad6-46b0-b998-8ba429afddef">

**Comment by tomivirkki** [comment]
The issue occurs in a client project, such as `docs` that uses the library. Inside the `react-components` project itself, this works as expected.

**Comment by web-padawan** [comment]
Ok, now I can reproduce it too. I also noticed that hand-written components e.g. `ComboBox`, `MultiSelectComboBox` and `Grid` and  have JSDoc shown, while generated ones e.g. `GridColumn` or `EmailField` do not.
