### ISSUE TITLE
Header renderer keeps creating new fields

### ISSUE THREAD

**Issue by Artur-** [vaadin/react-components#146]
Given
```
  const [headerLabel, setHeaderLabel] = useState("Initial");
  return (
    <Grid items={["a"]}>
      <GridColumnGroup
        headerRenderer={() => (
          <TextField
            label={headerLabel}
            onInput={(e) => {
              setHeaderLabel((e.target as any).value);
            }}
          ></TextField>
        )}
      >
        <GridColumn headerRenderer={() => <>header</>}>
          {() => <>"Hello"</>}
        </GridColumn>
      </GridColumnGroup>
    </Grid>
  );
```

You cannot enter anything in the field as every keystroke updates the state, causes a re-render and that re-render creates a new instance of text field

**Comment by Lodin** [comment]
AFAIK, due to underlying implementation of the `headerRenderer`, each update of the function causes re-render of the whole grid. I'd suggest using `useCallback` for the `headerRenderer` function here.

**Comment by Artur-** [comment]
That works, thanks! Should it be the default somehow?

**Comment by Lodin** [comment]
Good question. @rolfsmeds, @web-padawan, @platosha, what do you think?

**Comment by platosha** [comment]
Hard to say. If we put `useCallback` on our side, this would then create an issue of getting up-to-date `headerLabel` state, wouldn't it?

**Comment by platosha** [comment]
The vision I have is very speculative at the moment, but here it is: maybe the `headerRenderer` React prop changes should not invoke the web component renderer, but should still somehow update existing rendering with portals to DOM refs received from the previous web component renderer callback round (or with an off-screen `DocumentFragment` node for initial rendering perhaps).

**Comment by Lodin** [comment]
We could use Lit approach putting a mutable function into an immutable one:

```ts
function Grid({ headerRenderer }) {
  const ref = useRef(headerRenderer);

  ref.current = headerRenderer;

  const webComponentHeaderRenderer = useCallback((...args) => {
    ref.current(...args);
  }, []);

  return <_Grid headerRenderer={webComponentHeaderRenderer} ... />
}

```

**Comment by tomivirkki** [comment]
Grid columns now have `header` and `footer` [shorthands](https://github.com/vaadin/react-components/pull/195) that don't have this issue:

```jsx
header={
  <TextField
    label={headerLabel}
    onInput={(e) => {
      setHeaderLabel((e.target as any).value);
    }}
  ></TextField>
}
```
