### ISSUE TITLE
Compile a list of properties that have incorrect JsDocs [2 days]

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/react-components#162]
As a part of this task we need to create a list of APIs that have incorrect JsDocs:
- Missing proper documentation
- Have references to the protected APIs

**Comment by web-padawan** [comment]
`Select`: same issue as for `ContextMenu` above. Note, these components use almost identical `tsx` files.

<img width="347" alt="Screenshot 2023-12-07 at 15 44 52" src="https://github.com/vaadin/react-components/assets/10589913/3b312de1-8841-4ad2-9571-292555326fb0">

**Comment by web-padawan** [comment]
`MultiSelectComboBox` in IntelliJ can't resolve properties from mixins (own properties e.g. `selectedItems` work fine):

<img width="225" alt="Screenshot 2023-12-08 at 11 03 49" src="https://github.com/vaadin/react-components/assets/10589913/814d69ae-89b2-4144-8cc6-9e9cf6ca4159">

**Comment by web-padawan** [comment]
`GridPro` exposes some of the protected API e.g. `_disabledChanged` and `_theme`.

<img width="595" alt="Screenshot 2023-12-08 at 12 51 06" src="https://github.com/vaadin/react-components/assets/10589913/199487fa-323b-4ef8-8dd6-85872f614d92">

Note: regular `Grid` also exposes `_scrollToFlatIndex` but not `_theme` and `_disabledChanged`.

**Comment by web-padawan** [comment]
Based on my [test project](https://github.com/web-padawan/test-react), VSCode correctly shows JSDoc for the following components authored in `tsx` files:

- `ComboBox`
- `ContextMenu`
- `Dialog`
- `Grid`
- `GridPro`
- `MultiSelectComboBox`
- `Notification`
- `Select`
- `VirtualList`

Pressing <kbd>Cmd</kbd> + click on a property / attribute set on these components opens the WC file where it is defined.
Example: with `<Select disabled>` the `disabled` attribute "go to definition" will open `DisabledMixin.d.ts` file.

For other (generated) components, <kbd>Cmd</kbd> + click opens the  React wrapper `.d.ts` file, which doesn't have JSDoc.

**Comment by web-padawan** [comment]
After #167 is merged, JSDoc comments for generated components are shown correctly. 
One exception is `placeholder` property which is present in `React.HTMLAttributes`.
