### ISSUE TITLE
Omit HTMLAttributes from Dialog and Notification

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/react-components#192]
Similarly to https://github.com/vaadin/react-components/pull/188, the majority of `HTMLAttributes` could be omitted from `Dialog` and `Notification` components since, like `GridColumn`, the host elements in the DOM are invisible.

**Comment by web-padawan** [comment]
Note: same applies to `ConfirmDialog`, `CookieConsent` and `LoginOverlay` components.
