### ISSUE TITLE
Rename to @vaadin/react-components

### ISSUE THREAD

**Issue by taefi** [vaadin/react-components#212]
As part of the journey toward a unified platform under Vaadin umbrella, the `@hilla/react-components` should be renamed to `@vaadin/react-components` before for the Platform release `24.4.0`. Details of the whole change are listed in vaadin/hilla#1904.

**Comment by web-padawan** [comment]
Note: apart from renaming, we should also align the version of `@vaadin/react-components` with that of web-components.
