### ISSUE TITLE
Code completion is slow in IntelliJ

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/react-components#214]
Code completion for anything regarding React components is very sluggish in IntelliJ: importing components, completing component names, getting suggestions for props etc. The following video is from an empty Vite React project that compares auto-complete for Vaadin React components vs. Shoelace React components:

https://github.com/vaadin/react-components/assets/357820/439aa79e-e071-4fe6-829a-e72761a6659d

Reproduction:
```
npm create vite@latest -- --template react-ts test-project
cd test-project
npm install @hilla/react-components @shoelace-style/shoelace
```

Then open the project in IntelliJ and start using components in `App.tsx`.

This doesn't reproduce in VS Code where everything is quite fast.

**Comment by yuriy-fix** [comment]
Was it reproducible with latest (ts HtmlElement attrs removed)?
