### ISSUE TITLE
Remove the generated Grid so IDEs are not confused

### ISSUE THREAD

**Issue by Artur-** [vaadin/react-components#224]
If you start a new Hilla project in IntelliJ and type `<Grid` + cmd-space in Hello world, you see this
![Screenshot 2024-01-18 at 10 30 25](https://github.com/vaadin/react-components/assets/260340/fa3235f2-a23b-4d34-83ae-808130919085)

which looks fine but when you select Grid, you see
![Screenshot 2024-01-18 at 10 29 54](https://github.com/vaadin/react-components/assets/260340/4a56f4c8-c536-4f66-bc0b-2daf690e59d2)

which looks like Grid should not be exported from something called `generated/Grid`

**Comment by web-padawan** [comment]
Note: this was also reported in https://github.com/vaadin/react-components/pull/221#discussion_r1455021445. It's unclear why only `Grid` seems to be affected.

**Comment by web-padawan** [comment]
Tested locally and it seems that #225 resolves this and makes the second `Grid` suggestion go away:

https://github.com/vaadin/react-components/assets/10589913/25508043-921c-485f-908f-794bcc482bda

**Comment by web-padawan** [comment]
Fixed in v24.4.0-alpha6.
