### ISSUE TITLE
Prototype splitting packages [2 days]

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/react-components#229]
Based on https://github.com/vaadin/platform/issues/4936, prototype creation of the monorepo with the following structure:

- src (split and moved correspondingly under `packages`)
- packages
  - react-components
    - ... src files of the commercial components
    - ... dependencies from `react-components-core`
  - react-components-core
    - ... src files of the free components

Let's use npm workspaces and update package.json and repo scripts accordingly.

**Comment by tarekoraby** [comment]
On the naming of packages, a strong recommendation from the product team: Let's use,

- `@vaadin/react-components` for the free components
- `@vaadin/react-components-pro` for the  pro components
