### ISSUE TITLE
Chart title is not updated using HMR when clearing it

### ISSUE THREAD

**Issue by Artur-** [vaadin/react-components#258]
If you have e.g.
```
<Chart title="Sales">
```

and change it to 
```
<Chart title="Sales 2024">
```

then the chart is redrawn in dev mode. However, if you change it to
```
<Chart title="">
```

or
```
<Chart>
```

then the chart is not updated

**Comment by yuriy-fix** [comment]
Closing in favour of https://github.com/vaadin/web-components/issues/7768.
