### ISSUE TITLE
(Date)TimePicker rounds times to minutes even if the interval is in seconds

### ISSUE THREAD

**Issue by cromoteca** [vaadin/react-components#31]
```jsx
<TimePicker
  label='Message received'
  value='15:45:08'
  step={1}
/>
```
shows `15:45:00`, while

```html
<vaadin-time-picker label="Message received" value="15:45:08" step="1"></vaadin-time-picker>
```
shows `15:45:08`. Is the step unit the same?

**Comment by web-padawan** [comment]
Could be related to this issue https://github.com/vaadin/web-components/issues/4168#issuecomment-1180437681

**Comment by platosha** [comment]
After discussion, decided to reorder props in the wrapper to mitigate this issue for `TimePicker` and `DateTimePicker` components.

For example, if we make sure the `value` prop is set at last, this should fix this issue.
