### ISSUE TITLE
Undeprecate "theme" property

### ISSUE THREAD

**Issue by platosha** [vaadin/react-components#32]
The `theme` property is marked as deprecated in web components, however using the attribute should be allowed.

Currently it is confusingly deprecated for React wrappers. It should be safe to keep `theme` prop supported without deprecation, as the property support removal from the component would not make any impact for React users.

**Comment by web-padawan** [comment]
Please note that `theme` property was deprecated intentionally, see https://github.com/vaadin/web-components/pull/3529

> ThemePropertyMixin allows specifying themes only via the theme attribute. However, since ThemePropertyMixin also defines a protected read-only property theme, it makes both Svelte and Vue consider that the theme attribute must be set via that property, which doesn't work because the property is read-only.
