### ISSUE TITLE
Suggestions missing for the first component added in VS code

### ISSUE THREAD

**Issue by cromoteca** [vaadin/react-components#36]
When I want to add the first wrapped component to a view in Visual Studio Code, I get no suggestions at all:

![image](https://user-images.githubusercontent.com/498086/202201950-a6eacd05-1a93-47fa-bce6-19e6d2a3b177.png)

Then, after adding the import manually, I get suggestions for the other ones:

![image](https://user-images.githubusercontent.com/498086/202202391-0c046e47-b74e-4598-a73c-1281a7cd0c14.png)

What's weird is that if I remove the import I added manually, the suggestions are lost again.

I tried to wait, reload, nothing seems to fix this.

**Comment by cromoteca** [comment]
I can reproduce it both on Linux and Windows.

**Comment by cromoteca** [comment]
Works fine in Idea

**Comment by platosha** [comment]
We cannot fix it, seems to be some kind of a bug in VSCode.
