### ISSUE TITLE
MessageInput onSubmit does not fire on submit

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/react-components#51]
The following code does not print anything to the console 
```
<MessageInput onSubmit={(e: any) => console.log(e)}/>
```

**Comment by marcushellberg** [comment]
Related: https://github.com/vaadin/web-components/issues/5258

**Comment by platosha** [comment]
Seems to be caused by https://github.com/vaadin/web-components/issues/5258, which already fixed. Closing for now, let me know if the issue occurs.
