### ISSUE TITLE
Support React component / JSX as MenuBar items

### ISSUE THREAD

**Issue by platosha** [vaadin/react-components#54]
The MenuBar component’s way to define items is through the respective property. The underlying web component API supports defining text items, as well as a custom `component` custom element name string or a DOM element. Both are not great options when it comes for using in React context, where naturally support for React components and / or JSX is expected.

**Comment by tomivirkki** [comment]
Prototype for a more React-friendly `items` API https://github.com/vaadin/react-components/tree/feat/items-component
