### ISSUE TITLE
`colspan` is marked as error

### ISSUE THREAD

**Issue by cromoteca** [vaadin/react-components#70]
`colspan` is marked as an error in code editor, server-side logs, and in the browser, although then it works after a refresh. See [example](https://github.com/cromoteca/component-docs/blob/2f8cdad575f6b496771176115aad7ceefa8c44a5/frontend/views/form-layout/FormLayoutSimple.tsx#L15).

Version 2.1.0-alpha1.

**Comment by platosha** [comment]
We can ignore `colspan` errors using, for example, `@ts-expect-error` for now.

Ideally the `<vaadin-form-layout>` web component should be updated to support specifying child colspan using a standard `data-*` attribute.

**Comment by rolfsmeds** [comment]
After some discussion, we've decided to introduce `data-colspan` as an alias to `colspan` on the web component. (If both are provided, `colspan` has priority)

**Comment by web-padawan** [comment]
There is now an option to set `data-colspan`. Closing.
