### ISSUE TITLE
`UploadFile` does not expose the `held` property

### ISSUE THREAD

**Issue by cromoteca** [vaadin/react-components#73]
That property is useful when using `onUploadBefore` to redirect the upload to an endpoint.

See https://github.com/cromoteca/component-docs/blob/c45298a3b8d24c53bebd78e671d930e5a615625d/frontend/views/upload/UploadSimple.tsx#L20 for an example.

**Comment by platosha** [comment]
As a workaround for now, you should be able to use `fileRef.current.held` with `// @ts-ignore`.
