### ISSUE TITLE
GridColumn is not a valid JSX element

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/react-components#77]
Hilla 2.0.2. With
```
import { Grid, GridColumn, } from "@hilla/react-components/Grid";
```
and using `<GridColumn/>`, I get

```
'GridColumn' cannot be used as a JSX component.
  Its instance type 'GridColumn<any>' is not a valid JSX element.
    Type 'GridColumn<any>' is missing the following properties from type 'ElementClass': render, context, setState, forceUpdate, and 3 more.
```

<img width="977" alt="Screenshot 2023-03-29 at 15 56 26" src="https://user-images.githubusercontent.com/883698/228686418-9143fdb8-9ee8-4851-920a-ba9127fc6c1c.png">

**Comment by cromoteca** [comment]
That's the wrong import: see https://github.com/vaadin/react-components/issues/68
