### ISSUE TITLE
Cannot set `path` when using fields in CRUD

### ISSUE THREAD

**Issue by cromoteca** [vaadin/react-components#79]
Consider code like this (simplified):
```html
<vaadin-crud>
  <vaadin-form-layout>
    <vaadin-text-field label="First name" path="firstName" required></vaadin-text-field>
  </vaadin-form-layout>
</vaadin-crud>
```

When translating to React, there's no `path` on `TextField`.

Version `"@hilla/react-components": "2.0.2"`.

**Comment by platosha** [comment]
The issue is caused by missing type definitions for the `path` property. As a temporary workaround, ignoring the error from TypeScript could help:

```tsx
<Crud items={crudData}>
  {/* @ts-expect-error TS2322: missing TypeScript definition for the "path" property */}
  <TextField path="name"></TextField>
</Crud>
````

**Comment by cromoteca** [comment]
Fixed in https://github.com/vaadin/react-components/pull/104
