### ISSUE TITLE
Cookie-Consent attributes are not considered

### ISSUE THREAD

**Issue by cromoteca** [vaadin/react-components#80]
I have this code:
```tsx
import { CookieConsent } from "@hilla/react-components/CookieConsent.js";

export default function CookieConsentLocalization() {
  return (
    <CookieConsent
      message="Tämä sivusto käyttää evästeitä parhaan kokemuksen tarjoamiseksi"
      dismiss="Selvä"
      learnMore="Lue lisää"
      learnMoreLink="https://vaadin.com/terms-of-service"
    />
  );
}
```
I see no error in the editor, yet those values are not shown in the application. But at the beginning I had forgotten to convert attribute names to camel case, and values for `learn-more` and `learn-more-link` _were_ picked up.

**Comment by yuriy-fix** [comment]
This issue has been added to the backlog priority queue for further investigation.
