### ISSUE TITLE
The tab attribute is not recognized

### ISSUE THREAD

**Issue by czp13** [vaadin/react-components#93]
Some customer notified me that tab attribute is not recognized and showing/causing TS error.

Screenshots:
![image](https://user-images.githubusercontent.com/61667986/233037958-8c23e824-ac9f-4754-b65c-0135f0d6fd1c.png)

![image](https://user-images.githubusercontent.com/61667986/233039104-3b02da1d-10a3-43a2-a01b-f1ba425cb9ff.png)

**Comment by czp13** [comment]
A potential workaround can be found below. I got this from internal channels from Vaadin Hilla experts:

> tab is a non-standard property, and since TypeScript knows nothing about it, there is no definition for it either. 
> The fast workaround could be to update the default interface somewhere, e.g. in 

```
<root>/src/types.d.ts file.
declare global {
  interface HTMLDivElement {
    tab: string;
  }
}
```

**Comment by platosha** [comment]
Declaring the `tab` attribute support on any `<div>` is not clean, as it does not make sense outside of the `<TabSheet>` component that actually recognizes this attribute.

The cleaner API idea that we came up with here is to add a helper function like so:
```tsx
<div {...tabSheetTab('tab-1')}>Panel 1</div>
```
