### ISSUE TITLE
Autocomplete for React components produces wrong imports on IntelliJ IDEA

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/react-components#98]
Similar to #64. It is still an issue in Hilla 2.0.5: components are imported in IntelliJ IDEA without the `.js` extension. But now, instead of generating an error, the components seems to be rendered and functioning just fine. 

![image](https://user-images.githubusercontent.com/42799254/235114381-ed1beba0-2ed9-41e5-8114-e98225406171.png)

**Comment by tarekoraby** [comment]
So, I'm not really sure if this is even a bug.

**Comment by tarekoraby** [comment]
> Does the application have `"type": "module"` in `package.json`?

yes

> And what's the value of `"moduleResolution"` in `tsconfig.json`?

`nodeNext`

>  You can try with a fresh application created from CLI.

I did. IntelliJ still imports components without `.js`, and those components still work fine (at least the Button).

**Comment by platosha** [comment]
Let me close this, as we have allowed imports without `.js` extension.

This has to be for both 2.0 and 2.1+, in order to support old code with `"moduleResolution": "node"` and the new default with `"moduleResolution": "bundler"`, which do not enforce extensions.
